package com.obe.model;

// Generated May 26, 2014 8:10:46 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Patient generated by hbm2java
 */
@Entity
@Table(name = "Patient", catalog = "obe")
public class Patient implements java.io.Serializable {

	private int idPatient;
	private int idUser;
	private String firstName;
	private String lastName;

	public Patient() {
	}

	public Patient(int idPatient, int idUser) {
		this.idPatient = idPatient;
		this.idUser = idUser;
	}

	public Patient(int idPatient, int idUser, String firstName, String lastName) {
		this.idPatient = idPatient;
		this.idUser = idUser;
		this.firstName = firstName;
		this.lastName = lastName;
	}

	@Id
	@Column(name = "idPatient", unique = true, nullable = false)
	public int getIdPatient() {
		return this.idPatient;
	}

	public void setIdPatient(int idPatient) {
		this.idPatient = idPatient;
	}

	@Column(name = "idUser", nullable = false)
	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	@Column(name = "firstName", length = 45)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "lastName", length = 45)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

}
