package com.obe.model;

// Generated May 26, 2014 8:10:46 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Program generated by hbm2java
 */
@Entity
@Table(name = "Program", catalog = "obe")
public class Program implements java.io.Serializable {

	private int idProgram;
	private Integer idPerson;
	private String name;
	private Date dateBegin;
	private Date dateCompleted;

	public Program() {
	}

	public Program(int idProgram) {
		this.idProgram = idProgram;
	}

	public Program(int idProgram, Integer idPerson, String name,
			Date dateBegin, Date dateCompleted) {
		this.idProgram = idProgram;
		this.idPerson = idPerson;
		this.name = name;
		this.dateBegin = dateBegin;
		this.dateCompleted = dateCompleted;
	}

	@Id
	@Column(name = "idProgram", unique = true, nullable = false)
	public int getIdProgram() {
		return this.idProgram;
	}

	public void setIdProgram(int idProgram) {
		this.idProgram = idProgram;
	}

	@Column(name = "idPerson")
	public Integer getIdPerson() {
		return this.idPerson;
	}

	public void setIdPerson(Integer idPerson) {
		this.idPerson = idPerson;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateBegin", length = 19)
	public Date getDateBegin() {
		return this.dateBegin;
	}

	public void setDateBegin(Date dateBegin) {
		this.dateBegin = dateBegin;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateCompleted", length = 19)
	public Date getDateCompleted() {
		return this.dateCompleted;
	}

	public void setDateCompleted(Date dateCompleted) {
		this.dateCompleted = dateCompleted;
	}

}
