package com.obe.model;

// Generated May 26, 2014 8:10:46 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Reinforcement generated by hbm2java
 */
@Entity
@Table(name = "Reinforcement", catalog = "obe")
public class Reinforcement implements java.io.Serializable {

	private int idReinforcement;
	private String name;
	private Integer idTrial;
	private Integer idResponse;

	public Reinforcement() {
	}

	public Reinforcement(int idReinforcement) {
		this.idReinforcement = idReinforcement;
	}

	public Reinforcement(int idReinforcement, String name, Integer idTrial,
			Integer idResponse) {
		this.idReinforcement = idReinforcement;
		this.name = name;
		this.idTrial = idTrial;
		this.idResponse = idResponse;
	}

	@Id
	@Column(name = "idReinforcement", unique = true, nullable = false)
	public int getIdReinforcement() {
		return this.idReinforcement;
	}

	public void setIdReinforcement(int idReinforcement) {
		this.idReinforcement = idReinforcement;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "idTrial")
	public Integer getIdTrial() {
		return this.idTrial;
	}

	public void setIdTrial(Integer idTrial) {
		this.idTrial = idTrial;
	}

	@Column(name = "idResponse")
	public Integer getIdResponse() {
		return this.idResponse;
	}

	public void setIdResponse(Integer idResponse) {
		this.idResponse = idResponse;
	}

}
