package com.obe.model;

// Generated May 26, 2014 8:10:46 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Response generated by hbm2java
 */
@Entity
@Table(name = "Response", catalog = "obe")
public class ResponseModel implements java.io.Serializable {
	// We named Response as ResponseModel instead because Response clashed with import javax.ws.rs.core.Response;

	private int idResponse;
	private String name;
	private Integer idTrial;
	private Integer idStimulus;
	private Boolean successful;

	public ResponseModel() {
	}

	public ResponseModel(int idResponse) {
		this.idResponse = idResponse;
	}

	public ResponseModel(int idResponse, String name, Integer idTrial,
			Integer idStimulus, Boolean successful) {
		this.idResponse = idResponse;
		this.name = name;
		this.idTrial = idTrial;
		this.idStimulus = idStimulus;
		this.successful = successful;
	}

	@Id
	@Column(name = "idResponse", unique = true, nullable = false)
	public int getIdResponse() {
		return this.idResponse;
	}

	public void setIdResponse(int idResponse) {
		this.idResponse = idResponse;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "idTrial")
	public Integer getIdTrial() {
		return this.idTrial;
	}

	public void setIdTrial(Integer idTrial) {
		this.idTrial = idTrial;
	}

	@Column(name = "idStimulus")
	public Integer getIdStimulus() {
		return this.idStimulus;
	}

	public void setIdStimulus(Integer idStimulus) {
		this.idStimulus = idStimulus;
	}

	@Column(name = "successful")
	public Boolean getSuccessful() {
		return this.successful;
	}

	public void setSuccessful(Boolean successful) {
		this.successful = successful;
	}

}
