package com.obe.model;

// Generated May 26, 2014 8:10:46 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Series generated by hbm2java
 */
@Entity
@Table(name = "Series", catalog = "obe")
public class Series implements java.io.Serializable {

	private int idSeries;
	private Integer idProgram;
	private Date date;
	private Integer personRunBy;
	private String type;

	public Series() {
	}

	public Series(int idSeries) {
		this.idSeries = idSeries;
	}

	public Series(int idSeries, Integer idProgram, Date date,
			Integer personRunBy, String type) {
		this.idSeries = idSeries;
		this.idProgram = idProgram;
		this.date = date;
		this.personRunBy = personRunBy;
		this.type = type;
	}

	@Id
	@Column(name = "idSeries", unique = true, nullable = false)
	public int getIdSeries() {
		return this.idSeries;
	}

	public void setIdSeries(int idSeries) {
		this.idSeries = idSeries;
	}

	@Column(name = "idProgram")
	public Integer getIdProgram() {
		return this.idProgram;
	}

	public void setIdProgram(Integer idProgram) {
		this.idProgram = idProgram;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "personRunBy")
	public Integer getPersonRunBy() {
		return this.personRunBy;
	}

	public void setPersonRunBy(Integer personRunBy) {
		this.personRunBy = personRunBy;
	}

	@Column(name = "type", length = 4)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
