package com.obe.model;

// Generated May 26, 2014 8:10:46 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Stimulus generated by hbm2java
 */
@Entity
@Table(name = "Stimulus", catalog = "obe")
public class Stimulus implements java.io.Serializable {

	private int idStimulus;
	private String name;
	private Integer idTrial;
	private String type;

	public Stimulus() {
	}

	public Stimulus(int idStimulus) {
		this.idStimulus = idStimulus;
	}

	public Stimulus(int idStimulus, String name, Integer idTrial, String type) {
		this.idStimulus = idStimulus;
		this.name = name;
		this.idTrial = idTrial;
		this.type = type;
	}

	@Id
	@Column(name = "idStimulus", unique = true, nullable = false)
	public int getIdStimulus() {
		return this.idStimulus;
	}

	public void setIdStimulus(int idStimulus) {
		this.idStimulus = idStimulus;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "idTrial")
	public Integer getIdTrial() {
		return this.idTrial;
	}

	public void setIdTrial(Integer idTrial) {
		this.idTrial = idTrial;
	}

	@Column(name = "type", length = 10)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
