package com.obe.model;

// Generated May 26, 2014 8:10:46 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TherapistPatients generated by hbm2java
 */
@Entity
@Table(name = "Therapist_Patients", catalog = "obe", uniqueConstraints = @UniqueConstraint(columnNames = {
		"idTherapist", "idPatient" }))
public class TherapistPatients implements java.io.Serializable {

	private int idTherapistPatients;
	private int idTherapist;
	private int idPatient;

	public TherapistPatients() {
	}

	public TherapistPatients(int idTherapistPatients, int idTherapist,
			int idPatient) {
		this.idTherapistPatients = idTherapistPatients;
		this.idTherapist = idTherapist;
		this.idPatient = idPatient;
	}

	@Id
	@Column(name = "idTherapistPatients", unique = true, nullable = false)
	public int getIdTherapistPatients() {
		return this.idTherapistPatients;
	}

	public void setIdTherapistPatients(int idTherapistPatients) {
		this.idTherapistPatients = idTherapistPatients;
	}

	@Column(name = "idTherapist", nullable = false)
	public int getIdTherapist() {
		return this.idTherapist;
	}

	public void setIdTherapist(int idTherapist) {
		this.idTherapist = idTherapist;
	}

	@Column(name = "idPatient", nullable = false)
	public int getIdPatient() {
		return this.idPatient;
	}

	public void setIdPatient(int idPatient) {
		this.idPatient = idPatient;
	}

}
