package com.obe.model;

// Generated May 26, 2014 8:10:46 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Therapist generated by hbm2java
 */
@Entity
@Table(name = "Therapist", catalog = "obe")
public class Therapist implements java.io.Serializable {

	private int idTherapist;
	private int idUser;
	private String firstName;
	private String lastName;

	public Therapist() {
	}

	public Therapist(int idTherapist, int idUser) {
		this.idTherapist = idTherapist;
		this.idUser = idUser;
	}

	public Therapist(int idTherapist, int idUser, String firstName,
			String lastName) {
		this.idTherapist = idTherapist;
		this.idUser = idUser;
		this.firstName = firstName;
		this.lastName = lastName;
	}

	@Id
	@Column(name = "idTherapist", unique = true, nullable = false)
	public int getIdTherapist() {
		return this.idTherapist;
	}

	public void setIdTherapist(int idTherapist) {
		this.idTherapist = idTherapist;
	}

	@Column(name = "idUser", nullable = false)
	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	@Column(name = "firstName", length = 45)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "LastName", length = 45)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

}
