package com.obe.model;

// Generated May 26, 2014 8:10:46 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Trial generated by hbm2java
 */
@Entity
@Table(name = "Trial", catalog = "obe")
public class Trial implements java.io.Serializable {

	private int idTrial;
	private Integer idSeries;
	private String name;
	private boolean passed;
	private String promptType;

	public Trial() {
	}

	public Trial(int idTrial, boolean passed) {
		this.idTrial = idTrial;
		this.passed = passed;
	}

	public Trial(int idTrial, Integer idSeries, String name, boolean passed,
			String promptType) {
		this.idTrial = idTrial;
		this.idSeries = idSeries;
		this.name = name;
		this.passed = passed;
		this.promptType = promptType;
	}

	@Id
	@Column(name = "idTrial", unique = true, nullable = false)
	public int getIdTrial() {
		return this.idTrial;
	}

	public void setIdTrial(int idTrial) {
		this.idTrial = idTrial;
	}

	@Column(name = "idSeries")
	public Integer getIdSeries() {
		return this.idSeries;
	}

	public void setIdSeries(Integer idSeries) {
		this.idSeries = idSeries;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "passed", nullable = false)
	public boolean isPassed() {
		return this.passed;
	}

	public void setPassed(boolean passed) {
		this.passed = passed;
	}

	@Column(name = "promptType", length = 3)
	public String getPromptType() {
		return this.promptType;
	}

	public void setPromptType(String promptType) {
		this.promptType = promptType;
	}

}
